# Generated by Django 6.0.1 on 2026-02-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete'), ('undo', 'Undo')], max_length=20)),
                ('model_affected', models.CharField(help_text='Name of the model that was affected', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data for undo operations (old values, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_undone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'user histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(help_text="Quantity with unit (e.g., '500g', '2 cups', '1 dozen')", max_length=100)),
                ('perishable', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='inventory_items', to='inventory.dietarytag')),
            ],
            options={
                'ordering': ['expiry_date', 'name'],
            },
        ),
    ]
