# Generated by Django 6.0.1 on 2026-02-16 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', 'expiry_date'], name='inventory_i_user_id_33b323_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', 'perishable'], name='inventory_i_user_id_6afec0_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-timestamp'], name='inventory_u_user_id_fe8501_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', 'is_undone'], name='inventory_u_user_id_696e3f_idx'),
        ),
    ]
