# Generated by Django 6.0.1 on 2026-02-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('ingredients_text', models.JSONField(default=list, help_text='List of ingredient strings with quantities')),
                ('generated_by_llm', models.BooleanField(default=False, help_text='Whether this recipe was AI-generated')),
                ('nutrition_info', models.JSONField(blank=True, default=dict, help_text='Nutritional information: calories, protein, carbs, fat, etc.')),
                ('match_score', models.FloatField(default=0.0, help_text="Score indicating how well this matches user's inventory (0-1)")),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this recipe is visible to the community')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeFork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_ingredients', models.JSONField(default=list, help_text='Modified ingredients list')),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom modifications to the original instructions')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
