# Generated by Django 6.0.1 on 2026-02-16 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Linked inventory items used in this recipe', related_name='used_in_recipes', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='inventory.dietarytag'),
        ),
        migrations.AddField(
            model_name='recipefork',
            name='forked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forked_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipefork',
            name='original_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_public', '-created_at'], name='recipes_rec_is_publ_bf1b57_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_by', '-created_at'], name='recipes_rec_created_ed0691_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-match_score'], name='recipes_rec_match_s_a382d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipefork',
            unique_together={('original_recipe', 'forked_by')},
        ),
    ]
